title: awesome-microbits-ks2
description: A primary-school-focused filter of carlosperate/awesome-microbit — curated for extension activities for more able KS2 pupils and primary code clubs.
theme: jekyll-theme-cayman
